# Generated by Django 3.2.5 on 2022-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0005_auto_20220405_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
