# Generated by Django 3.2.5 on 2022-04-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0006_auto_20220405_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
