# Generated by Django 3.2.5 on 2022-04-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0008_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
