# Generated by Django 3.2.5 on 2022-04-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0015_auto_20220414_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
