# Generated by Django 3.2.5 on 2022-04-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0016_alter_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
