# Generated by Django 3.2.5 on 2022-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0017_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
