# Generated by Django 3.2.5 on 2022-04-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0018_transaction_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
