# Generated by Django 3.2.5 on 2022-04-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0019_alter_transactionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
