# Generated by Django 3.2.5 on 2022-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_amonze', '0020_alter_transactionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='evidence',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
